name: Deploy App

on:
  workflow_call:
    inputs:
      rollback:
        required: false
        type: string
        default: "false"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Print rollback input
        run: |
          echo "📥 Received rollback = ${{ inputs.rollback }}"

      - name: Decide action
        run: |
          if [ "${{ inputs.rollback }}" == "true" ]; then
            echo "🚨 This is a rollback deployment!"
          else
            echo "✅ Proceeding with normal deployment."
          fi

      - name: Save deployment log
        run: |
          echo "{ \"rollback\": \"${{ inputs.rollback }}\" }" > deploy-log.json


      - name: Upload deployment log
        uses: actions/upload-artifact@v4
        with:
          name: deploy-log
          path: deploy-log.json
